  

<div class="container">
    <div class="row">
        <div class="col-lg-12" style="padding: 0px;">
            <ol class="breadcrumb" style="background-color:rgba(0,0,0,0.5);">
                <li class="breadcrumb-item"><a href="<?= $this->baseUrl("admin-local") ?>">Início</a></li>
                <li class="breadcrumb-item active" style="color: white;" aria-current="page">Tarifas Municipais</li>
            </ol>
        </div>

        <div class="col-lg-12" style="padding: 0px;">

            <div class="card" style="background-color:rgba(0,0,0,0.7);">
                <div class="card-header">
                    <button class="btn btn-info clickable card-collapsed">Cadastrar</button>
                </div>
                <div class="card-body" style="display: none;">
                    <form class="jumbontron" method="post"  style="background-color:rgba(0,0,0,0.2); color: white; padding: 15px;">
                        <div class="form-group">
                            <div class="row">

                                <div class="col-lg-4" >
                                    <label for="descricao" id="label">Categoria</label><label  style="color:red" id="label">*</label>
                                    <!-- <input type="text" class="form-control" id="inicio" placeholder="Local inicial da linha"> -->
                                    <a data-toggle="modal" data-target="#exampleModalCenter-categoria" id="">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer; font-size: 11px" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="categoria">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaCategoria" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                   </div>

                               </div>
                               <div class="col-lg-3" >
                                <label for="data_inicio" id="label">Data Início</label><label  style="color:red" id="label">*</label>
                                <input type="date" id="data_inicio" class="form-control" style="margin-bottom: 5px">
                                <div class="alert-lt alert-danger validaInicio"  align="center" style="display:none" role="alert">
                                   Campo obrigatório
                               </div>
                           </div>
                           <div class="col-lg-3">

                             <label for="data_fim" id="label">Data Fim</label><label  style="color:red" id="label">*</label>
                             <input type="date" id="data_fim" class="form-control" style="margin-bottom: 5px">
                             <div class="alert-lt alert-danger validaFim"  align="center" style="display:none" role="alert">
                               Campo obrigatório
                           </div>
                       </div>
                       <div class="col-lg-2">


                         <label for="valor" id="label">Valor</label><label  style="color:red" id="label">*</label>

                         <div class="input-group xmb-2" style="margin-bottom: 5px">
                          <div class="input-group-prepend">
                              <span class="input-group-text" id="basic-addon1">R$</span>
                          </div>
                          <input type="text" id="valor" class="form-control"  >
                      </div>


                      <div class="alert-lt alert-danger validaValor"  align="center" style="display:none" role="alert">
                       Campo obrigatório
                   </div>
               </div>

           </div>
           <div class="row">
               <div class="col-lg-4"></div>

               <div class="col-lg-6">
                   <div class="alert-lt alert-danger validaIf"  align="center" style="display:none" role="alert">
                       A data de início não pode ser maior que a data de fim.
                   </div>
               </div>
               <div class="col-lg-2"></div>

           </div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="alert-lt alert-danger validaHoje"  align="center" style="display:none" role="alert">
                       A data de início não pode ser menor que a data atual.
                   </div>
                   <div class="alert-lt alert-danger validaDobanco"  align="center" style="display:none" role="alert">
                       O período não pode conflitar com o período de uma tarifa já cadastrada para este trajeto.
                   </div>
               </div>
           </div>











       </div>	


       <button class="btn btn-info btn-block cadastrar-tarifa" type="button">
        Cadastrar
    </button>
</form>
</div>
</div>
</div>


<!-- fim container form-->

<div class="col-lg-12">
    <table class="table"  style="margin-top: 1%; background-color:rgba(0,0,0,0.7); padding: 0px; color: white; text-align: center">
        <thead >
            <tr>
                <th scope="col">Trajeto</th>
               
                <th scope="col">Valor</th>
                <th scope="col">Data de início</th> <!-- atualizar para tabela da tarifa  -->
                <th scope="col">Data de fim</th>

            </tr>
        </thead>
        <tbody>


        </tbody>
        <? foreach ($this->listaDasTarifas as $tarifa): ?>

            <?php 
                $inicio = date_create($tarifa['data_inicio']);
                $fim = date_create($tarifa['data_fim']);  
                  ?>
            
            <tr>
               <td><?= $tarifa['descricao'] ?>    </td>
               
               <td>R$ <?= $tarifa['valor'] ?>    </td>
               <td><?= date_format($inicio, 'd/m/Y') ?>    </td>
               <td><?= date_format($fim, 'd/m/Y') ?>    </td>
           </tr>

       <? endforeach; ?>
   </table>
</div>
</div>
</div>






<div class="modal fade" id="exampleModalCenter-categoria" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Trajeto</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <select multiple class="form-control" id="sel" style="height: 270px;">
                    <? foreach ($this->listaDosTrajetos as $categoria): ?>
                        <option  value="<?= $categoria['id_trajeto'] ?>"><?= $categoria['descricao']; ?></option>
                    <? endforeach; ?>
                </select>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" id="alocar-categoria" data-dismiss="modal">Ok</button>


            </div>
        </div>
    </div>
</div>











