<div class="container">
	<link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/forma-pagamento.css") ?> />
  <div class="row">
  	<div class="col-lg-4"></div>
  	<div class="col-lg-4">
<form method="POST">
	<br>
	<br>
<div class="card bg-light mb-3" style="max-width: 18rem;">
  <nav class="navbar navbar-expand-lg navbar-dark bg-light">
	<div class="card-body">
  <div class="form-group">
    <label for="">Descrição</label>
    <input type="text" class="form-control" id="descricao" name="descricao" placeholder="Digite a descrição">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Tarifa</label>
    <input type="text" class="form-control" id="tarifa" name="tarifa" placeholder="Digite a taxa">
  </div>
  <button type="submit" class="btn btn-block btn-primary">Cadastrar</button>
  <a href="../public/menuinicial" class="btn btn-block btn-danger btn-primary">Voltar</a>
</div>
</div>
</div>
  <div class="col-lg-4"></div>
</form>

 </div>

</div>