<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/definirTarifa.css") ?> />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<script src="js/jquery-3.3.1.js"> </script>

<div class="container fundo">
  <div class="row">		
		<div class="col-sm-12" style="background-color:rgba(0,0,0,0.4); color: white">
			<center><H2>Definir Tarifas</h2></center>
			<div class="row"> 
            <div class="col">
							<Center><H4>Trajetos</H4></Center>
							<div class="alert alert-info">
								<div class="form">
									<div class="listaDeTrajetos">
									<!-- O name é justamente o nome do Trajeto! -->
									<form>
										<div class="checkbox">
											<label><input type="checkbox" name="abc" id="myCheck" onclick="selecionarCheckbox(this); return true;">Trajeto 1</label>
										</div>
										<div class="checkbox">
											<label><input type="checkbox" name="def" id="myCheck" onclick="selecionarCheckbox(this); return true;">Trajeto 2</label>
										</div>
										<div class="checkbox">
											<label><input type="checkbox" name="ghi" id="myCheck" onclick="selecionarCheckbox(this); return true;">Trajeto 3</label>
										</div>
									</form>
									</div>
								</div>
        			</div>
						</div>

            <div class="col">
							<Center><H4>Trajetos selecionados</H4></Center>
							<div class="list-group listaTrajetosSelecionados" id="div1">
							</div>
							<form>
							<Center><H4>Alterar Tarifa</H4>
								<div class="input-group validarReal">
									<span class="input-group-addon">R$</span>
									<input type="number" class="form-control" min="1" max="10" placeholder="Real" id="campoTarifa" required>
									<span class="input-group-addon">.00</span>
								</div>
								<h4>Término da Vigência</h4>
								<div class="form-group">
									<div id="filterDate2">
										<!-- Datepicker as text field -->         
										<div class="input-group date" data-date-format="dd.mm.yyyy">
											<input  type="date" class="form-control" placeholder="dd.mm.yyyy" required>
											<div class="input-group-addon " >
												<span class="glyphicon glyphicon-th" ></span>
											</div>
										</div>
									</div>    
								</div>
								<div style="margin-bottom: 5%;">
									<button type="button" class="btn btn-warning">Voltar</button>
									<button type="submit" class="btn btn-success">Pronto</button>
								</div>
								</Center>
							</form>
						</div>

			</div>
		</div>			
	</div>
</div>

<script type="text/javascript">
	
	var trajetos = [];

    function doalert(obj) {
			if(obj.getAttribute("id") == 1){	
        obj.setAttribute("class", "list-group-item active");
				obj.setAttribute("id", 0);
        return false;
			} else {
				obj.setAttribute("class", "list-group-item");
				obj.setAttribute("id", 1);
				return true;
			}
    }

		function selecionarCheckbox(obj) {
			if(obj.checked == true){	
				var para = document.createElement("a");
				para.setAttribute("href", "");
				para.setAttribute("class", "list-group-item");
				para.setAttribute("id", 1);
				var text = obj.getAttribute("name");
				para.setAttribute("name", text);
				para.setAttribute("onclick", "doalert(this); return false;");
				var node = document.createTextNode(text);
				para.appendChild(node);
				var element = document.getElementById("div1");
				element.appendChild(para);
				trajetos.push(para);
        return false;
			} else {
				
				obj.setAttribute("class", "list-group-item");
				obj.setAttribute("id", 1);
				trajetos.pop(obj);
				return true;
			}
    }

		function datepickerfunction() {
			$('.input-group.date').datepicker({format: "dd.mm.yyyy"}); 
		};

</script>