<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/definirTarifa.css") ?> />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<script src="js/jquery-3.3.1.js"> </script>

<div class="container fundo">
  <div class="row">		
		<div class="col-sm-12" style="background-color:rgba(0,0,0,0.4); color: white">
			<center><H2>Definir Tarifas</h2></center>
			<div class="row"> 
            <div class="col">
							<Center><H4>Trajetos</H4></Center>
							<div class="alert alert-info">
								<div class="form">
									<div class="listaDeTrajetos">
										<label class="radio">
												<input value="1" type="radio">Trajeto 1
										</label>
										<label class="radio">
												<input value="2" type="radio">Trajeto 2
										</label>
										<label class="radio">
												<input value="3" type="radio">Trajeto 3
										</label>
										<label class="radio">
												<input value="4" type="radio">Trajeto 4
										</label>
									</div>
								</div>
        			</div>
						</div>

            <div class="col">
							<Center><H4>Informações do Trajeto</H4></Center>
							<ul class="list-group listaTrajetosSelecionados">
								<li class="list-group-item list-group-item-success">Trajeto 1</li>
								<li class="list-group-item list-group-item-info">Trajeto 2</li>
								<li class="list-group-item list-group-item-warning">Trajeto 3</li>
								<li class="list-group-item list-group-item-danger">Trajeto 4</li>
							</ul>
							<form>
							<Center><H4>Alterar Tarifa</H4>
								<div class="input-group validarReal">
									<span class="input-group-addon">R$</span>
									<input type="number" class="form-control" min="1" max="10" placeholder="Real" required>
									<span class="input-group-addon">.00</span>
								</div>
								<h4>Término da Vigência</h4>
								<div class="form-group">
									<div id="filterDate2">
										<!-- Datepicker as text field -->         
										<div class="input-group date" data-date-format="dd.mm.yyyy">
											<input  type="date" class="form-control" placeholder="dd.mm.yyyy" required>
											<div class="input-group-addon" >
												<span class="glyphicon glyphicon-th"></span>
											</div>
										</div>
									</div>    
								</div>
								<script type="text/javascript">
								$(function () {
									$('.input-group.date').datepicker({format: "dd.mm.yyyy"}); 
											});
								</script>

								<div style="margin-bottom: 5%;">
									<button type="button" class="btn btn-warning">Voltar</button>
									<button type="submit" class="btn btn-success">Pronto</button>
								</div>
								</Center>
							</form>
						</div>

			</div>
		</div>			
	</div>
</div>