<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link href="../ProjetoRPV/public/dist/css/bootstrap.min.css" rel="stylesheet">
	
	<title>Editar Motorista</title>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

	


</head>
<body style="background-image: url(../../../dist/imagens/fundo.png);" >

	<h1 id="titulo">
		Editar Motorista
	</h1>

	<div class="container" style="background-color: rgba(0,0,0,0.8); padding-bottom: 0px;">
		
		
		<form  method="post"  >
			<div class="form-group" >
				
				<h2 style="color:white">Cadastro de Motoristas</h2>
				<div class="row" >
					
					
					<div class="col-8" >
						<label for="nome-cobrador" id="label" >Nome</label>
						<input type="hidden" id="id-motorista" name="id-motorista" value="<?php echo $this->motorista->getId_motorista(); ?>">
  			 			<input type="text" name="nome-motorista" class="form-control" id="nome-motorista" placeholder="Insira o nome completo" value="<?php echo $this->motorista->getNome(); ?>">

					</div>
					<div class="col-4" >
						<label for="cpf" id="label">CPF</label>
  			 			<input type="text" name="cpf-motorista" class="form-control" id="cpf-motorista" placeholder="Digite o CPF" value="<?php echo $this->motorista->getCpf(); ?>">

					</div>
					

				</div>
				<div class="row">
					<div class="col-11">
						

					</div>
					<div class="col-1" style="padding: 10px;">
						<button class="btn btn-outline-success btn-lt" type="submit" id="gravar">
							Gravar
						</button>

					</div>
				</div>
				

			</div>



		</form>
	</div>

	
	
	
<!-- </div> -->
	
	<script>
		
		

	</script>

</div>
</div>

</body>
</html>