<img src="<?= $this->baseUrl("dist/img/loading.gif") ?>" class="img-loading hidden" alt="carregando...">

<div class="container">
    <div class="row">
        <div class="col-lg-12" style="padding: 0px;">
            <ol class="breadcrumb" style="background-color:rgba(0,0,0,0.5);">
                <li class="breadcrumb-item"><a href="<?= $this->baseUrl("venda") ?>">Início</a></li>
                <li class="breadcrumb-item active" style="color: white;" aria-current="page">Venda</li>
            </ol>
        </div>

        <div class="col-lg-12" style="padding: 0px;">
            <div class="card" style="background-color:rgba(0,0,0,0.5);">
                <div class="card-header">
                    <button class="btn btn-info clickable card-collapsed">Cadastrar</button>
                </div>
                <div class="card-body" style="display: none;">
                    <div class="jumbontron" method="post" style="background-color:rgba(0,0,0,0.2); color: white; padding: 15px; border-radius: 0.25rem;">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-3">
                                    <label>Poltrona:</label>
                                    <a data-toggle="modal" data-target="#poltronas" id="poltrona">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>


                                            <input type="text" class="form-control" src=""  disabled id="descricao-trecho-inicio">
                                        </div>
                                    </a>
                                </div>
                                <div class="col-lg-3">
                                    <label>Seguro:</label>
                                    <input type="text" class="form-control" id="valor">
                                    <!--data-lock="form"-->
                                </div>
                                <div class="col-lg-3">
                                    <label>Forma de Pagamento:</label>
                                    <a data-toggle="modal" data-target="#formas-pagamento" id="forma-pagamento">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>


                                            <input type="text" class="form-control" src=""  disabled id="descricao-trecho-inicio">
                                        </div>
                                    </a>
                                </div>
                                <div class="col-lg-3">
                                    <label>Valor:</label>
                                    <input type="text" class="form-control" id="valor">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-5">
                                    <br>
                                    <div class="alert alert-danger descricao" role="alert" style="display: none;">
                                        O campo <strong>Descrição</strong> é obrigatório.
                                    </div>
                                </div>
                                <div class="col-lg-1"></div>
                                <div class="col-lg-6">
                                    <div class="alert alert-danger valor" role="alert" style="display: none;">
                                        O campo <strong>Valor</strong> é obrigatório.
                                    </div>
                                    <div class="alert alert-danger valor-incorreto" role="alert" style="display: none;">
                                        O campo <strong>Valor</strong> deve conter no mínimo 5 digitos.
                                    </div>
                                    <div class="alert alert-danger dia" role="alert" style="display: none;">
                                        Verifique o <strong>dia</strong> correto para data de término!
                                    </div>
                                    <div class="alert alert-danger mes" role="alert" style="display: none;">
                                        Verifique o <strong>mês</strong> correto para data de término!
                                    </div>
                                    <div class="alert alert-danger ano" role="alert" style="display: none;">
                                        Verifique o <strong>ano</strong> correto para data de término!
                                    </div>
                                    <div class="alert alert-danger data" role="alert" style="display: none;">
                                        Verifique a <strong>data</strong> correta para término!
                                    </div>
                                </div>
                            </div>
                            <!--<hr>-->
                        </div>
                        <hr>
                    </div>
                </div>
            </div>

            <!-- fim container form-->
            <div class="col-lg-12">
                <table class="table"  style="margin-top: 2%; background-color:rgba(0,0,0,0.5); padding: 0px; color: white;">
                    <thead >
                        <tr>
                            <th scope="col">Passageiro</th>
                            <th scope="col">Poltrona</th>
                            <th scope="col">Seguro</th>
                            <th scope="col">Pagamento</th>
                            <th scope="col">Valor</th>
                            <th scope="col">Ações</th>
                        </tr>
                    </thead>
                    <tbody>


                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="poltronas" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Selecione a sua Poltrona</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <select multiple class="form-control" id="sel5" style="height: 270px;">
                    
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="Poltrona na janela" value="">1</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" style="margin-right: 33%;" title="Poltrona no corredor" value="">2</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">3</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">4</option>
                    
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">5</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" style="margin-right: 33%;" title="" value="">6</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">7</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">8</option>
                    
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">9</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" style="margin-right: 33%;" title="" value="">10</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">11</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">12</option>
                    
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">13</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" style="margin-right: 33%;" title="" value="">14</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">15</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">16</option>
                    
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">17</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" style="margin-right: 33%;" title="" value="">18</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">19</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">20</option>
                    
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">21</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" style="margin-right: 33%;" title="" value="">22</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">23</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">24</option>
                    
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">25</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" style="margin-right: 33%;" title="" value="">26</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">27</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">28</option>
                    
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">29</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" style="margin-right: 33%;" title="" value="">30</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">31</option>
                    <option class="btn btn-success btn-block btn-labeled col-lg-2 float-left" title="" value="">32</option>
                </select>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" id="alocar-trecho-inicio" data-dismiss="modal">Ok</button>


            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="formas-pagamento" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Selecione a Forma de Pagamento</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <select multiple class="form-control" id="sel5" style="height: 270px;">
                    <option  value="">Crédito</option>
                    <option  value="">Débito</option>
                    <option  value="">Dinheiro</option>
                    <option  value="">Pontos</option>
                </select>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" id="alocar-trecho-inicio" data-dismiss="modal">Ok</button>


            </div>
        </div>
    </div>
</div>