<div class="container">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <form class="jumbotron" method="post">
                <h3>PampaBus</h3>
                <hr>
                <div class="form-group">
                    <label for="exampleInputEmail1">Login</label>
                    <div class="input-group"  style="padding-bottom: 5px">
                        <div class="input-group-prepend" >
                            <span class="input-group-text" id="validationTooltipUsernamePrepend">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                        <input type="text" class="form-control" name="nome_usuario" autocomplete="off" maxlength="25">
                    </div>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Senha</label>
                    <div class="input-group"  style="padding-bottom: 5px">
                        <div class="input-group-prepend" >
                            <span class="input-group-text" id="validationTooltipUsernamePrepend">
                                <i class="fa fa-key"></i>
                            </span>
                        </div>
                        <input type="password" class="form-control" name="senha" autocomplete="off" maxlength="8">
                    </div>
                    <button type="submit" class="btn btn-primary float-right">Entrar</button>
                </div>
                <!--<a href="#">Cadastrar</a>-->
            </form>

            <div class="col-lg-4"></div>
        </div>
    </div>
</div>