<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
            <div class="col-lg-2">
                <a href="<?= $this->baseUrl('/admin-local') ?>" accesskey="c" style="text-decoration: none;">
                    <button class="btn btn-success btn-block btn-labeled" title="">
                        <span class="btn-label-secratario"><i class="fas fa-user"></i></span>
                        <h6>
                            Administrador<br>
                            <u>L</u>ocal
                        </h6>
                    </button>
                </a>
            </div>
            <div class="col-lg-2">
                <a href="<?= $this->baseUrl('admin-geral') ?>" accesskey="a" style="text-decoration: none;">
                    <button class="btn btn-success btn-block btn-labeled" title="">
                        <span class="btn-label-secratario"><i class="fas fa-user"></i></span>
                        <h6>
                            Administrador<br>
                            <u>G</u>eral
                        </h6>
                    </button>
                </a>
            </div>
            <div class="col-lg-2">
                <a href="<?= $this->baseUrl('secretario') ?>" accesskey="a" style="text-decoration: none;">
                    <button class="btn btn-success btn-block btn-labeled" title="">
                        <span class="btn-label-secratario"><i class="fas fa-user"></i></span>
                        <h6>
                            Administrador<br>
                            <u>S</u>ecretário
                        </h6>
                    </button>
                </a>
            </div>
            <div class="col-lg-6"></div>
    </div>
</div>