<div class="container">
	<link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/forma-pagamento.css") ?> />
  <div class="row">
  	<div class="col-lg-4"></div>
  	<div class="col-lg-4">
<form>
	<br>

<div class="card bg-light mb-3" style="max-width: 18rem;">
  <nav class="navbar navbar-expand-lg navbar-dark bg-light">
	<div class="card-body">
   <div class="form-group">
    <label for="exampleInputPassword1">Selecione a(as) categoria(as)</label>


<div class="custom-control custom-checkbox ">
  <input type="checkbox" class="custom-control-input" id="customCheck1">
  <label class="custom-control-label" for="customCheck1">Comum</label>
</div>
<div class="custom-control custom-checkbox">
  <input type="checkbox" class="custom-control-input" id="customCheck1">
  <label class="custom-control-label" for="customCheck1">Executivo</label>
</div>
<div class="custom-control custom-checkbox">
  <input type="checkbox" class="custom-control-input" id="customCheck1">
  <label class="custom-control-label" for="customCheck1">Leito</label>
</div>
  </div>




  <div class="form-group">
    <label for="exampleInputEmail1">Marca</label>
    <input type="email" class="form-control" id="descricao" placeholder="Digite a fabricante do onibus">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Modelo</label>
    <input type="password" class="form-control" id="taxa" placeholder="Digite o modelo do onibus">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Ano de Fabricação</label>
    <input type="password" class="form-control" id="taxa" placeholder="Digite o ano de fabricação">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">N° Assentos</label>
    <input type="password" class="form-control" id="taxa" placeholder="Digite o numero de assentos no onibus">
  </div>


  <button type="submit" class="btn btn-block btn-primary">Cadastrar</button>
  <a href="../public/menuinicial" class="btn btn-block btn-danger btn-primary">Voltar</a>

</div>
</div>
</div>
  <div class="col-lg-4"></div>
</form>

 </div>

</div>