<div class="container">
    <div class="row">
        <div class="col-lg-12" style="padding: 0px;">
            <ol class="breadcrumb" style="background-color:rgba(0,0,0,0.5);">
                <li class="breadcrumb-item"><a href="<?= $this->baseUrl("admin-local") ?>">Início</a></li>
                <li class="breadcrumb-item"><a href="<?= $this->baseUrl("apolice") ?>">Apólices</a></li>
                <li class="breadcrumb-item active" style="color: white;" aria-current="page">Visualizar</li>
            </ol>
        </div>

        <div class="col-lg-12" style="background-color:rgba(0,0,0,0.5);">
            <? foreach ($this->apolicePorId as $apolice): ?>
            <hr>
                <h4 style="color: white;"><strong style="color: white;">Apólice: </strong><? echo $apolice['descricao'] ?></h4>
                <h4 style="color: white;"><strong style="color: white;">Data de término: </strong><? echo $apolice['data_fim'] ?></h4>
            <? endforeach; ?>

            <table class="table" style="text-align: center; margin-top: 2%; background-color:rgba(0,0,0,0.5); padding: 0px; color: white;">
                <thead >
                    <tr>
                        <th>placa</th>
                        <th>ano</th>
                        <th>tipo</th>
                    </tr>
                </thead>
                <tbody>

                    <? foreach ($this->listarOnibusPorIdApolice as $onibus): ?>
                        <tr>
                            <td><?= $onibus['placa'] ?></td>
                            <td><?= $onibus['ano'] ?></td>
                            <td><?= $onibus['tipo'] ?></td>
                        </tr>
                    <? endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>