<img src="<?= $this->baseUrl("dist/img/loading.gif") ?>" class="img-loading hidden" alt="carregando...">


<div class="container">
    <div class="row">
        <div class="col-lg-12" style="padding: 0px;">
            <ol class="breadcrumb" style="background-color:rgba(0,0,0,0.5);">
                <li class="breadcrumb-item"><a href="<?= $this->baseUrl("admin-local") ?>">Início</a></li>
                <li class="breadcrumb-item active" style="color: white;" aria-current="page">Rodoviárias Locais</li>
            </ol>
        </div>

        <div class="col-lg-12" style="padding: 0px;">
            <div class="card" style="background-color:rgba(0,0,0,0.5);">
                <div class="card-header">
                    <button class="btn btn-info" id="botaoAdicionarConcessao" data-toggle="modal" data-target="#modal-mensagem"> 
                        Cadastrar
                    </button>
                    &nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    <a href="<?= $this->baseUrl("rodoviarias-passagem-local?tipo=1") ?>"> <button class="btn btn-default">
                            <i class="fas fa-search" style="color:black"></i> Ativos </button></a>
                    <a href="<?= $this->baseUrl("rodoviarias-passagem-local?tipo=2") ?>"> <button class="btn btn-default">
                            <i class="fas fa-search" style="color:black"></i> Inativos </button></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="text" placeholder="Digite a cidade" id="buscaCidade" name="buscaCidade" class="btn btn-default" style="width:20%;"
                           maxlength="60">&nbsp;
                    <button class="btn btn-default" align="right" onclick="window.location.href = 'rodoviarias-passagem-local' + '?cidade=' + buscaCidade.value">
                        <i class="fas fa-search" style="color:black"></i>Buscar</button>  

                </div>
            </div>
        </div>


        <div class="col-lg-12"> 
            <table class="table text-center table-bordered" style="background-color:rgba(0,0,0,0.5); color: white">
                <tr class="text-primary">
                    <th colspan="6">
                <center><h3>Rodoviárias Conveniadas</h3></center>
                </th>
                </tr>
                <br>
                <tr>
                    <th><center>Nome</center></th>
                <th><center>Cidade</center></th>
                <th><center>Estado</center></th>
                <th><center>Responsável</center></th>
                <th><center>Data de Início</center></th>
                <th><center>Situação</center></th>
                </tr>
                <tbody>
                    <? foreach ($this->listarTodasRodoviarias as $rodoviaria): ?>
                        <tr>
                            <td> <?= $rodoviaria['nome'] ?></td>
                            <td> <?= $rodoviaria['cidade'] ?></td>
                            <td> <?= $rodoviaria['estado'] ?></td>
                            <td> <?= $rodoviaria['responsavel'] ?></td>
                            <td> <?= $rodoviaria['data_inicio'] ?></td>
                            <td>
                                <?php if ($rodoviaria['status_rodoviaria'] === 'ATIVO'): ?>
                                    <div class="btn-group" id="status" data-toggle="buttons">
                                        <label class="btn btn-default plug status-on btn-on aberto active" onclick="editarStatus(<?= $rodoviaria['codRodoviaria'] ?>, 'ATIVO')">
                                            <input type="radio" name="plug" checked="checked">ATIVO</label>
                                        <label class="btn btn-default plug status-off btn-off fechado" onclick="editarStatus(<?= $rodoviaria['codRodoviaria'] ?>, 'INATIVO')">
                                            <input type="radio" name="plug">INATIVO</label>
                                    </div>
                                <?php endif; ?>

                                <?php if ($rodoviaria['status_rodoviaria'] === 'INATIVO'): ?>
                                    <div class="btn-group" id="status" data-toggle="buttons">
                                        <label class="btn btn-default status-on btn-on plug aberto" onclick="editarStatus(<?= $rodoviaria['codRodoviaria'] ?>, 'ATIVO')">
                                            <input type="radio" name="plug" checked="checked">ATIVO</label>
                                        <label class="btn btn-default status-off btn-off plug fechado active" onclick="editarStatus(<?= $rodoviaria['codRodoviaria'] ?>, 'INATIVO')">
                                            <input type="radio" name="plug">INATIVO</label>
                                    </div>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <? endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal-mensagem" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <center><h4 class="modal-title">ADICIONAR RODOVIÁRIA</h4></center>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container"> 
                    <div class="row">
                        <div class="col-lg-1"></div>
                        <div class="col-lg-10">
                            <form class="jumbotron" method="post">
                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label">Nome <strong style="color: red;" title="Campo Obrigatório">*</strong></label>
                                    <div class="col-lg-9">
                                        <div class="input-group input-append date" id="">   	    	
                                            <input type="text" autocomplete="off" class="form-control" placeholder="Qual o nome da rodoviária?" id="nome" name="nome">
                                            <span class="input-group-addon add-on"><span class="glyphicon glyphicon-road"></span></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label">Cidade <strong style="color: red;" title="Campo Obrigatório">*</strong></label>
                                    <div class="col-lg-9">
                                        <div class="input-group input-append date" id="">   	    	
                                            <input type="text" autocomplete="off" class="form-control" placeholder="Qual a cidade?" id="cidade" name="cidade">
                                            <span class="input-group-addon add-on"><span class="glyphicon glyphicon-road"></span></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label">Estado <strong style="color: red;" title="Campo Obrigatório">*</strong></label>
                                    <div class="col-lg-9">
                                        <div class="input-group input-append date" id="">   	    	
                                            <input type="text" autocomplete="off" class="form-control" placeholder="Qual o estado?" id="estado" name="estado">
                                            <span class="input-group-addon add-on"><span class="glyphicon glyphicon-road"></span></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label">Responsável <strong style="color: red;" title="Campo Obrigatório">*</strong></label>
                                    <div class="col-lg-9">
                                        <div class="input-group input-append date" id="">   	    	
                                            <input type="text" autocomplete="off" class="form-control" placeholder="Quem é o responsável pela rodoviária?" id="responsavel" name="responsavel">
                                            <span class="input-group-addon add-on"><span class="glyphicon glyphicon-road"></span></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label" >Data de Inicio <strong style="color: red;" title="Campo Obrigatório">*</strong></label>										    	
                                    <div class="col-lg-9">
                                        <div class="">
                                            <input type="date" class="form-control" placeholder="Data de início" id="data_inicio" name="data_inicio" />
                                            <span class="input-group-addon add-on"><span class="glyphicon glyphicon-calendar"></span></span>
                                        </div>
                                    </div>
                                </div>

                                <button type="button" class="btn btn-success btn-block cadastrar" id="cadastrar">
                                    Cadastrar
                                </button>
                            </form>
                        </div>
                        <div class="col-lg-1"></div>
<!--                        <script src="js/somenteletra.js"></script>
                        <script src="js/somentenumero.js"></script>
                        <script src="js/valida_email.js"></script>
                        <script src="js/nomecompleto.js"></script>
                        <script src="js/numtelefone.js"></script>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
