  

<div class="container">
    <div class="row">
        <div class="col-lg-12" style="padding: 0px;">
            <ol class="breadcrumb" style="background-color:rgba(0,0,0,0.5);">
                <li class="breadcrumb-item"><a href="<?= $this->baseUrl("admin-local") ?>">Início</a></li>
                <li class="breadcrumb-item active" style="color: white;" aria-current="page">Horários Linhas</li>
            </ol>
        </div>

        <div class="col-lg-12" style="padding: 0px;">
            <div class="card" style="background-color:rgba(0,0,0,0.5);">
                <div class="card-header">
                    <button class="btn btn-info clickable card-collapsed">Cadastrar</button>
                </div>
                <div class="card-body" style="display: none;">
                    <form class="jumbontron" method="post"  style="background-color:rgba(0,0,0,0.2); color: white; padding: 15px;">
                        <div class="form-group">
                            <div class="row">
                                
                                <div class="col-lg-12" >
                                    <label for="descricao" id="label">Linha</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-linha" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="linha">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaLinha" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>

                            </div>
                            <br>
                    <div class="row" style="background-color: rgba(0,0,0,0.4); padding-left: 25px">

                    <input type="checkbox" id="checkSegunda" class="form-check-input"> Segunda-feira 
                        
                    </div>
                    <div class="row" id="segunda">
                        
                        <div class="col-lg-2">
                        <label for="segSaida">Horário de saída</label><label  style="color:red" id="label">*</label>
                            <input type="time" id="saidaSegunda" class="form-control">
                        </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Motorista</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-motorista-segunda" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="motoristaSegunda">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Ônibus</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-onibus-segunda" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="onibusSegunda">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>

                                
                    </div>

                    
                    <div class="row" style="background-color: rgba(0,0,0,0.4); padding-left: 25px">
                        
                    <input type="checkbox" id="checkTerca" class="form-check-input"> Terça-feira 
                        
                    </div>
                    <div class="row" id="terca">
                        
                        <div class="col-lg-2">
                        <label for="segSaida">Horário de saída</label><label  style="color:red" id="label">*</label>
                            <input type="time" id="saidaTerca" class="form-control">
                        </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Motorista</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-motorista-terca" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="motoristaTerca">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Ônibus</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-onibus-terca" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="onibusTerca">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>
                    </div>
                    <div class="row" style="background-color: rgba(0,0,0,0.4); padding-left: 25px">

                    <input type="checkbox" id="checkQuarta" class="form-check-input"> Quarta-feira 
                        
                    </div>
                    <div class="row" id="quarta">
                        
                        <div class="col-lg-2">
                        <label for="segSaida">Horário de saída</label><label  style="color:red" id="label">*</label>
                            <input type="time" id="saidaQuarta" class="form-control">
                        </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Motorista</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-motorista-quarta" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="motoristaQuarta">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Ônibus</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-onibus-quarta" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="onibusQuarta">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>
                    </div>
                    <div class="row" style="background-color: rgba(0,0,0,0.4); padding-left: 25px">

                    <input type="checkbox" id="checkQuinta" class="form-check-input"> Quinta-feira 
                        
                    </div>
                    <div class="row" id="quinta">
                        
                        <div class="col-lg-2">
                        <label for="segSaida">Horário de saída</label><label  style="color:red" id="label">*</label>
                            <input type="time" id="saidaQuinta" class="form-control">
                        </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Motorista</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-motorista-quinta" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="motoristaQuinta">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Ônibus</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-onibus-quinta" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="onibusQuinta">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>
                    </div>
                    <div class="row" style="background-color: rgba(0,0,0,0.4); padding-left: 25px">

                    <input type="checkbox" id="checkSexta" class="form-check-input"> Sexta-feira 
                        
                    </div>
                    <div class="row" id="sexta">
                        
                        <div class="col-lg-2">
                        <label for="segSaida">Horário de saída</label><label  style="color:red" id="label">*</label>
                            <input type="time" id="saidaSexta" class="form-control">
                        </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Motorista</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-motorista-sexta" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="motoristaSexta">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Ônibus</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-onibus-sexta" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="onibusSexta">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>
                    </div>
                    <div class="row" style="background-color: rgba(0,0,0,0.4); padding-left: 25px">

                    <input type="checkbox" id="checkSabado" class="form-check-input"> Sábado 
                        
                    </div>
                    <div class="row" id="sabado">
                        
                        <div class="col-lg-2">
                        <label for="segSaida">Horário de saída</label><label  style="color:red" id="label">*</label>
                            <input type="time" id="saidaSabado" class="form-control">
                        </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Motorista</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-motorista-sabado" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="motoristaSabado">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Ônibus</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-onibus-sabado" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="onibusSabado">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>
                    </div>
                    <div class="row" style="background-color: rgba(0,0,0,0.4); padding-left: 25px">

                    <input type="checkbox" id="checkDomingo" class="form-check-input"> Domingo
                        
                    </div>

                    <div class="row" id="domingo">
                        
                        <div class="col-lg-2">
                        <label for="segSaida">Horário de saída</label><label  style="color:red" id="label">*</label>
                            <input type="time" id="saidaDomingo" class="form-control">
                        </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Motorista</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-motorista-domingo" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="motoristaDomingo">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório
                                  </div>

                                </div>
                        <div class="col-lg-5" >
                                    <label for="descricao" id="label">Ônibus</label><label  style="color:red" id="label">*</label>
                                    
                                    <a data-toggle="modal" data-target="#exampleModalCenter-onibus-domingo" id="validaInicio">
                                        <div class="input-group"  style="padding-bottom: 5px">
                                            <div class="input-group-prepend" >
                                                <span style="cursor: pointer;" class="input-group-text" id="validationTooltipUsernamePrepend">
                                                    Selecionar
                                                </span>
                                            </div>
                                            
                                            
                                            <input type="text" class="form-control" src=""  disabled id="onibusDomingo">
                                        </div>
                                    </a>
                                    <div class="alert-lt alert-danger validaInicio" align="center" style="display:none" role="alert">
                                       Campo obrigatório 
                                  </div>

                                </div>
                    </div>

                    </div>	

                    
                   
                    <button class="btn btn-info btn-block cadastrar-linha-dia" type="button">
                        Cadastrar
                    </button>
                </form>
            </div>
        </div>
    </div>


    <!-- fim container form-->

    
            </div>
        </div>

        <div class="col-lg-12">
        <table class="table"  style="margin-top: 1%; background-color:rgba(0,0,0,0.7); padding: 0px; color: white; text-align: center">
            <thead >
                <tr>
                    <th scope="col">Descrição</th>
                    <th scope="col">Origem</th>
                    <th scope="col">Saída</th> <!-- implementar com moment  -->
                    <th scope="col">Dia</th>
                    <th scope="col">Detalhes</th>
                </tr>
            </thead>
            <tbody>
                <? foreach ($this->listaDasLinhasDia as $linhad): ?>
                    <tr>
                        <td><?= $linhad['descricao'] ?>    </td>
                        <td>    <?= $linhad['origem'] ?></td>
                        <td>    <?= $linhad['horario_inicio'] ?></td>
                        <td>    <?= $linhad['dia'] ?></td>
                        

                        
                       
                       

                                        <td>

                                        
                                           <a class="btn btn-primary btn-labeled" href="<?= $this->baseUrl('linhaDia/linhaDias/id_linha/' . $linhad['id_linha'].'/id_dia/' . $linhad['id_dia'].'/inicio/' . $linhad['horario_inicio']) ?>">
                                    <span class="btn-label">
                                        <i class="fas fa-eye"></i>
                                    </span>
                                    Visualizar detalhes
                                </a>

                                            
 

                                    </td>


                                </tr>
                            <? endforeach; ?>

                        </tbody>
                    </table>
                </div>




       

        <div class="modal fade" id="exampleModalCenter-linha" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione a linha</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel" style="height: 270px;">
                            <? foreach ($this->listaDasLinhas as $linha): ?>
                                <option  value="<?= $linha['id_linha'] ?>"><?= $linha['descricao']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-linha" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>


 <!-- modais segunda        -->
        <div class="modal fade" id="exampleModalCenter-onibus-segunda" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Ônibus</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel3" style="height: 270px;">
                            <? foreach ($this->listaDosOnibus as $onibus): ?>
                                <option  value="<?= $onibus['id_onibus_viagem'] ?>"><?= $onibus['modelo']."  ".$onibus['chassi']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-onibus-segunda" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>

         <div class="modal fade" id="exampleModalCenter-motorista-segunda" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Motorista</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel2" style="height: 270px;">
                            <? foreach ($this->listaDosMotoristas as $motorista): ?>
                                <option  value="<?= $motorista['id_motorista'] ?>"><?= $motorista['nome']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-motorista-segunda" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>


        <!-- modais terça        -->
        <div class="modal fade" id="exampleModalCenter-onibus-terca" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Ônibus</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel4" style="height: 270px;">
                            <? foreach ($this->listaDosOnibus as $onibus): ?>
                                <option  value="<?= $onibus['id_onibus_viagem'] ?>"><?= $onibus['modelo']."  ".$onibus['chassi']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-onibus-terca" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>

         <div class="modal fade" id="exampleModalCenter-motorista-terca" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Motorista</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel5" style="height: 270px;">
                            <? foreach ($this->listaDosMotoristas as $motorista): ?>
                                <option  value="<?= $motorista['id_motorista'] ?>"><?= $motorista['nome']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-motorista-terca" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>


        <!-- modais quarta        -->
        <div class="modal fade" id="exampleModalCenter-onibus-quarta" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Ônibus</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel7" style="height: 270px;">
                            <? foreach ($this->listaDosOnibus as $onibus): ?>
                                <option  value="<?= $onibus['id_onibus_viagem'] ?>"><?= $onibus['modelo']."  ".$onibus['chassi']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-onibus-quarta" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>

       <div class="modal fade" id="exampleModalCenter-motorista-quarta" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Motorista</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel6" style="height: 270px;">
                            <? foreach ($this->listaDosMotoristas as $motorista): ?>
                                <option  value="<?= $motorista['id_motorista'] ?>"><?= $motorista['nome']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-motorista-quarta" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>


        <!-- modais quinta        -->
        <div class="modal fade" id="exampleModalCenter-onibus-quinta" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Ônibus</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel9" style="height: 270px;">
                            <? foreach ($this->listaDosOnibus as $onibus): ?>
                                <option  value="<?= $onibus['id_onibus_viagem'] ?>"><?= $onibus['modelo']."  ".$onibus['chassi']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-onibus-quinta" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>

       <div class="modal fade" id="exampleModalCenter-motorista-quinta" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Motorista</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel8" style="height: 270px;">
                            <? foreach ($this->listaDosMotoristas as $motorista): ?>
                                <option  value="<?= $motorista['id_motorista'] ?>"><?= $motorista['nome']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-motorista-quinta" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>


        <!-- modais sexta        -->
        <div class="modal fade" id="exampleModalCenter-onibus-sexta" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Ônibus</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel11" style="height: 270px;">
                            <? foreach ($this->listaDosOnibus as $onibus): ?>
                                <option  value="<?= $onibus['id_onibus_viagem'] ?>"><?= $onibus['modelo']."  ".$onibus['chassi']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-onibus-sexta" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>

         <div class="modal fade" id="exampleModalCenter-motorista-sexta" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Motorista</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel10" style="height: 270px;">
                            <? foreach ($this->listaDosMotoristas as $motorista): ?>
                                <option  value="<?= $motorista['id_motorista'] ?>"><?= $motorista['nome']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-motorista-sexta" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>


        <!-- modais sábado        -->
        <div class="modal fade" id="exampleModalCenter-onibus-sabado" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Ônibus</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel13" style="height: 270px;">
                            <? foreach ($this->listaDosOnibus as $onibus): ?>
                                <option  value="<?= $onibus['id_onibus_viagem'] ?>"><?= $onibus['modelo']."  ".$onibus['chassi']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-onibus-sabado" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="exampleModalCenter-motorista-sabado" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Motorista</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel12" style="height: 270px;">
                            <? foreach ($this->listaDosMotoristas as $motorista): ?>
                                <option  value="<?= $motorista['id_motorista'] ?>"><?= $motorista['nome']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-motorista-sabado" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>


        <!-- modais domingo        -->
        <div class="modal fade" id="exampleModalCenter-onibus-domingo" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Ônibus</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel15" style="height: 270px;">
                            <? foreach ($this->listaDosOnibus as $onibus): ?>
                                <option  value="<?= $onibus['id_onibus_viagem'] ?>"><?= $onibus['modelo']."  ".$onibus['chassi']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-onibus-domingo" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>

         <div class="modal fade" id="exampleModalCenter-motorista-domingo" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Motorista</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel14" style="height: 270px;">
                            <? foreach ($this->listaDosMotoristas as $motorista): ?> 
                                <option  value="<?= $motorista['id_motorista'] ?>"><?= $motorista['nome']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar-motorista-domingo" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>

        




 




