<div class="container">
	<link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/forma-pagamento.css") ?> />
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
     <ol class="breadcrumb" style="background-color:rgba(0,0,0,0.7);">
      <li>
        <a href="<?= $this->baseUrl('menuinicial') ?>">
          menuinicial/
        </a>
        <a href="<?= $this->baseUrl('forma-pagamento') ?>">
          forma_pagamento/
        </a>
      </li>
      <li class="active">
       editar
     </li>
   </ol>
   <form method="POST">


    <div class="card mb-3" style="background-color:rgba(0,0,0,0.7);">
      <div class="card-body"> 
        <div class="form-group">
          <input type="hidden" id="id_pagamento" name="id_pagamento" value="<?php echo $this->pagamento->getId_pagamento(); ?>">
          <label for="">Descrição</label>
          <input type="text" class="form-control" id="descricao" name="descricao" placeholder="Digite a descrição" value="<?php echo $this->pagamento->getDescricao(); ?>">
        </div>

        <br>
        <button type="button" class="col-lg-2 btn btn-primary editarFormaPagamento">Salvar</button>
        <a href="<?= $this->baseUrl('forma-pagamento') ?>" class="col-lg-2 btn btn-primary">Voltar</a>
      </div>
    </div>
  </form>

</div>
<div class="col-lg-2"></div>
</div>
</div>
