<div class="container">
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-2"></div>
            <div class="col-lg-2 col-md-2 col-sm-2">
                <a href="<?= $this->baseUrl('/onibus-urbano/cadastrar') ?>" accesskey="c" style="text-decoration: none;">
                    <button class="btn btn-success btn-block btn-labeled" title="(Alt+c) Cadastrar Ônibus Urbano">
                        <span class="btn-label-secratario"><i class="fas fa-bus-alt"></i></span>
                        <h6>
                            <u>C</u>adastrar
                        </h6>
                        <h6>
                            Ônibus Urbano
                        </h6>
                    </button>
                </a>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-2">
                <a href="<?= $this->baseUrl('onibus-intermunicipal/cadastrar') ?>" accesskey="a" style="text-decoration: none;">
                    <button class="btn btn-success btn-block btn-labeled" title="(Alt+a) Cadastrar Ônibus Intermunicipal">
                        <span class="btn-label-secratario"><i class="fas fa-bus"></i></span>
                        <h6>
                            C<u>a</u>dastrar
                        </h6>
                        <h6>
                            Ônibus Intermunic.
                        </h6>
                    </button>
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4"></div>
    </div>
</div>