<div class="container">
    <div class="row">
        <div class="col-lg-1"></div>
            <div class="col-lg-2">
                <a href="<?= $this->baseUrl('/onibus-urbano') ?>" accesskey="c" style="text-decoration: none;">
                    <button class="btn btn-success btn-block btn-labeled" title="(Alt+u) Ônibus Urbanos">
                        <span class="btn-label-secratario"><i class="fas fa-bus-alt"></i></span>
                        <h6>
                            Ônibus<br>
                            <u>U</u>rbanos
                        </h6>
                    </button>
                </a>
            </div>
            <div class="col-lg-2">
                <a href="<?= $this->baseUrl('onibus-intermunicipal') ?>" accesskey="a" style="text-decoration: none;">
                    <button class="btn btn-success btn-block btn-labeled" title="(Alt+i) Ônibus Intermunicipais">
                        <span class="btn-label-secratario"><i class="fas fa-bus"></i></span>
                        <h6>
                            Ônibus<br>
                            <u>I</u>ntermunicipais
                        </h6>
                    </button>
                </a>
            </div>
            <div class="col-lg-2">
                <a href="<?= $this->baseUrl('cobrador') ?>" accesskey="c" style="text-decoration: none;">
                    <button class="btn btn-success btn-block btn-labeled" title="(Alt+i) Ônibus Intermunicipais">
                        <span class="btn-label-secratario"><i class="fas fa-user"></i></span>
                        <h6>
                            Gerenciar<br>
                            Cobradores
                        </h6>
                    </button>
                </a>
            </div>
            <div class="col-lg-2">
                <a href="<?= $this->baseUrl('motorista') ?>" accesskey="m" style="text-decoration: none;">
                    <button class="btn btn-success btn-block btn-labeled" title="">
                        <span class="btn-label-secratario"><i class="fas fa-user"></i></span>
                        <h6>
                            Gerenciar<br>
                            Motoristas
                        </h6>
                    </button>
                </a>
            </div>
            <div class="col-lg-2">
                <a href="<?= $this->baseUrl('parada-onibus') ?>" accesskey="p" style="text-decoration: none;">
                    <button class="btn btn-success btn-block btn-labeled" title="">
                        <span class="btn-label-secratario"><i class="fas fa-user"></i></span>
                        <h6>
                            Gerenciar<br>
                            Paradas
                        </h6>
                    </button>
                </a>
            </div>
            <div class="col-lg-1"></div>
    </div>
</div>