<div class="container">
    <link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/forma-pagamento.css") ?> />
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form>
                <br>

                <div class="card bg-light mb-3">
                    <nav class="navbar navbar-expand-lg navbar-dark bg-light">
                        <div class="card-body">


                            <div class="form-group">
                                <label for="exampleInputEmail1">Usuário</label>
                                <input type="email" class="form-control" id="nome_usuario" placeholder="Escolha um nome de usuário">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Senha</label>
                                <input type="email" class="form-control" id="senha" placeholder="Escolha uma senha">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Confirme a senha</label>
                                <input type="email" class="form-control" id="confirmarSenha" placeholder="Confirme a senha">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Nome Completo</label>
                                <input type="password" class="form-control" id="nomeCompleto" placeholder="Digite o nome completo">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Data de Nascimento:</label>
                                <input type="date" class="form-control" id="dataNascimento" placeholder="Digite a data de nascimento">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">CPF:</label>
                                <input type="password" class="form-control" id="cpf" placeholder="Digite o cpf">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">RG:</label>
                                <input type="password" class="form-control" id="rg" placeholder="Digite o RG">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Celular:</label>
                                <input type="password" class="form-control" id="celular" placeholder="Digite o celular">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Rua:</label>
                                <input type="password" class="form-control" id="rua" placeholder="Digite a rua em que reside">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">N°:</label>
                                <input type="password" class="form-control" id="numeroCasa" placeholder="N° da casa">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Bairro:</label>
                                <input type="password" class="form-control" id="bairro" placeholder="Bairro">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Anexe o Comprovante de Residência:</label>
                                <input type="file" class="form-control" id="comprovanteResidencia" placeholder="Anexo documento que comprove a residência">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Anexe o Comprovante de Matrícula:</label>
                                <input type="file" class="form-control" id="comprovanteMatricula" placeholder="Anexe o comprovante de matrícula">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Selecione o benefício:</label>


                                <div class="custom-control custom-checkbox ">
                                    <input type="checkbox" class="custom-control-input" id="customCheck1">
                                    <label class="custom-control-label" for="customCheck1">Nenhum</label>
                                </div>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="customCheck1">
                                    <label class="custom-control-label" for="customCheck1">Meia Passagem</label>
                                </div>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="customCheck1">
                                    <label class="custom-control-label" for="customCheck1">Isenção</label>
                                </div>
                            </div>


                            <button type="submit" class="btn btn-block btn-primary">Cadastrar</button>
                            <a href="../public/menuinicial" class="btn btn-block btn-danger btn-primary">Voltar</a>

                        </div>
                </div>
            </form>
        </div>
        <div class="col-lg-3"></div>

    </div>

</div>