<div class="col-lg-12" style="padding: 0px;">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card" style="background-color:rgba(0,0,0,0.5);">
                    <div class="container labelsForm">
                        <form>
                            <Center> 
                            <!-- Conjunto de divs-linha para cada campo do form-->                      
                            <h6>Do cargo</h6> 
                            <div class="form-group form-control-sm row ">
                                <label for="example-search-input" class="col-6 col-form-label">Cargo</label>
                                <div class="col-xs-9 ">
                                    <select class="custom-select" id="inputGroupSelect01" required>
                                        <option selected label="Selecione um cargo." disabled></option>
                                        <option value="1">Administrador Local</option>
                                        <option value="2">Administrador Local</option>
                                        <option value="3">Cobrador</option>
                                        <option value="4">Gerente de Recursos Humanos</option>
                                        <option value="5">Motorista</option>
                                        <option value="6">Secretário</option>
                                        <option value="7">Vendedor</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">Salario</label>
                                <div class="col-xs-9">
                                    <input class="form-control" type="number" value="998" min="998" max="10000" step="0.01" data-number-to-fixed="2" data-number-stepfactor="100" id="" required>
                                </div>
                            </div>
                                         
                            <h6>Do funcionário</h6>
                            
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">Nome</label>
                                <div class="col-xs-9">
                                    <input class="form-control" type="text" placeholder="Digite o nome" id="" required>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">Data de Nascimento</label>
                                <div class="col-xs-9">
                                    <input type="date" name="data" id="data" class="form-control" placeholder="dd/mm/aaaa" required>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">CPF</label>
                                <div class="col-xs-9">
                                <input type="text" name="cpf" id="cpf" placeholder="XXX.XXX.XXX-XX" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">RG</label>
                                <div class="col-xs-9">
                                <input type="text" name="rge" id="rg" placeholder="XXXXXXXXXX" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">CTPS</label>
                                <div class="col-xs-9">
                                    <input type="text" name="ctps" id="ctps" placeholder="Número Série UF" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">PIS</label>
                                <div class="col-xs-9">
                                    <input type="text" name="pis" id="pis" placeholder="XXX.XXXXX.XX-X" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">CNH</label>
                                <div class="col-xs-9">
                                    <input type="text" name="cnh" id="cnh" placeholder="XXXXXXXXXXX" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">Telefone</label>
                                <div class="col-xs-9">
                                    <input type="text" name="telefone" id="telefone" placeholder="(XX)XXXXX-XXXX"class="form-control" required>
                                </div>
                            </div>
                            <br>
                            </Center>
                        
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="background-color:rgba(0,0,0,0.5);">
                    <div class="container labelsForm">
                        
                            <Center> 
                            <!-- Conjunto de divs-linha para cada campo do form-->
                            <h6></h6> 
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">E-mail</label>
                                <div class="col-xs-9">
                                    <input type="text" name="email" id="email" placeholder="nome@mail.com" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">Data de Admissão</label>
                                <div class="col-xs-9">
                                    <input type="date" name="dataAdmissao" id="dataAdmissao" placeholder="dd/mm/aaaa" class="form-control" required>
                                </div>
                            </div>                         
                            <div class="form-group form-control-sm row">
                                <label for="example-search-input" class="col-6 col-form-label">Cidade</label>
                                <div class="col-xs-9">
                                    <select class="custom-select" id="inputCidade" required>
                                        <option selected label="Selecione a cidade." disabled></option>
                                        <option value="1">Alegrete</option>
                                        <option value="2">Cachoeira do Sul</option>
                                        <option value="3">Porto Alegre</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">Endereço</label>
                                <div class="col-xs-9">
                                    <input class="form-control" type="text" maxlength="30" placeholder="Digite o endereço" id="" required>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">Numero da casa</label>
                                <div class="col-xs-9">
                                    <input class="form-control" type="number" min="0" id="" required>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">Bairro</label>
                                <div class="col-xs-9">
                                    <input class="form-control" type="text" maxlength="30" placeholder="Digite o bairro" id="" required>
                                </div>
                            </div>

                            <h6>Do acesso</h6>

                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">Nome de usuário</label>
                                <div class="col-xs-9">
                                    <input class="form-control" type="text" maxlength="15" placeholder="Digite o usuário" id="" required>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">Senha</label>
                                <div class="col-xs-9">
                                <input type="password" name="pass" id="pass" maxlength="30" placeholder="Sua senha" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group form-control-sm row">
                                <label class="col-6 col-form-label">Confirme a senha</label>
                                <div class="col-xs-9">
                                <input type="password" name="pass" id="pass" maxlength="30" placeholder="Sua senha denovo" class="form-control" required>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-sm-6">
                                    <button type="submit" for="exampleFormControlFile1" class="btn btn-success btn-sm btn-block">Pronto</button>
                                </div>
                                <div class="col-sm-6">
                                    <button type="reset" class="btn btn-warning btn-sm btn-block" >Limpar campos</button> 
                                </div>
                            </div>
                            <br>
                            </Center>
                        </form>
                    </div>
                </div>
            </div>      
        </div>
    </div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
        $("#data").mask("99/99/9999");
        $("#rg").mask("9999999999");
		$("#cpf").mask("999.999.999-99");
        $('#ctps').mask('9999999 99999 SS');
        $('#pis').mask('999.99999.99-9');
        $('#cnh').mask('99999999999');
        $("#telefone").mask("(99) 99999-9999");
        $('#dataAdmissao').mask('99/99/9999');     
    });
    
<? foreach ($this->listaDeCidade as $cidade): ?>
    
        var para = document.createElement("option");
        var textv = document.createTextNode(<?= $cidade->getNome() ?>);
        var id = document.create
        para.appendChild(textv);

        var att = document.createAttribute("id");
        att.value = <?= $cobrador->getId_cidade() ?>;
        para.setAttributeNode(att);

        var element = document.getElementById("inputCidade");
        element.appendChild(para);
         
        </script>
    
<? endforeach; ?>
