<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/categoriaPassageiro.css") ?> />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

<body>

    <div class="container fundo">

        <div class="table-responsive" style="background-color:rgba(0,0,0,0.5); color: white">
            <table class="table table-bordered text-center" style="background-color:rgba(0,0,0,0.5); color: white">
                <tr class="text-primary">
                    <th class="fundoTransparente" colspan="4" style="background-color:rgba(0,0,0,0.5); color: white">
                <center><h3>Novas Solicitações de Benefícios</h3></center>
                </th>
                </tr>
                <tr>
                    <th class="fundoTransparente" colspan="1" style="background-color:rgba(0,0,0,0.5); color: white"><center>CPF</center></th>
                <th class="fundoTransparente" colspan="1" style="background-color:rgba(0,0,0,0.5); color: white"><center>Nome</center></th>
                <th class="fundoTransparente" colspan="1" style="background-color:rgba(0,0,0,0.5); color: white"> <center>Data de Solicitação</center></th>
                <th class="fundoTransparente" colspan="1" style="background-color:rgba(0,0,0,0.5); color: white"><center>Situação</center></th>
                </tr>
                <tr>
                    <? foreach ($this->listarBeneficios as $solicitacaobeneficio): ?>
                    <tr>
                        <td> <?= $solicitacaobeneficio['cpf'] ?></td>		                        
                        <td> <?= $solicitacaobeneficio['nome'] ?></td>
                        <td> <?= $solicitacaobeneficio['data_solicitacao'] ?></td>
                        <td> <?= $solicitacaobeneficio['descricao_situacao'] ?>
                            <a href="<?= '#myModal' . $solicitacaobeneficio['id_solicitacao'] ?>" class="btn btn-default" data-toggle="modal"> 
                                <i class="fas fa-edit" style="color:black"></i>
                            </a>
                        </td>
                    </tr>
                <? endforeach; ?>
                </tr>

            </table>

        </div>
        <!-- Modal -->
        <? foreach ($this->listarBeneficios as $solicitacaobeneficio): ?>
            <div class="modal fade" id="<?= 'myModal' . $solicitacaobeneficio['id_solicitacao'] ?>" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">PESSOA IDOSA</h4>
                            <button type="button" class="close" data-dismiss="modal">
                                <span>&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="container-fluid"> 
                                <div class="row">
                                    <div class="table-responsive">
                                        <form method="post">
                                            <div class="form-group">
                                                <div class="col-sm-6">
                                                    <label >Nome completo:</label>
                                                    <input type="text" disabled class="form-control" value="<?= $solicitacaobeneficio['nome'] ?> " name="nomeCompleto" id="nomeCompleto">
                                                    <label >Data de nascimento:</label>
                                                    <input type="text" disabled class="form-control" value="<?= $solicitacaobeneficio['data_nascimento'] ?>" name="dataNascimento" id="dataNascimento">
                                                    <label >CPF:</label>
                                                    <input type="text" disabled class="form-control" value="<?= $solicitacaobeneficio['cpf'] ?>" name="cpf" id="cpf">
                                                    <label >RG:</label>
                                                    <input type="text" disabled class="form-control" value="<?= $solicitacaobeneficio['rg'] ?>" name="rg" id="rg">
                                                    <label> Celular: </label>
                                                    <input type="text" disabled class="form-control" value="<?= $solicitacaobeneficio['celular'] ?>" name="celular" id="celular">
                                                    <label>Conceder Benefício:</label>
                                                    <button class="btn-group btn-group-toggle" data-toggle="buttons">
                                                        <label class="btn btn-outline-dark">
                                                            <input type="radio" name="options" id="nenhum" name="nenhum" autocomplete="off"> Nenhum
                                                        </label>
                                                        <label class="btn btn-outline-dark">
                                                            <input type="radio" name="options" id="meiaPassagem" name="meiaPassagem" autocomplete="off"> Meia-Passagem
                                                        </label>
                                                        <label class="btn btn-outline-dark">
                                                            <input type="radio" name="options" id="isencao" name="isencao" autocomplete="off"> Isenção
                                                    </button>
                                                    <br><button type="submit" name="botaoConceder" id="botaoConceder" class="btn btn-success">Salvar</button>		
                                                </div>
                                                <div class="col-sm-6">
                                                    <label> Rua: </label>
                                                    <input type="text" disabled class="form-control" value="<?= $solicitacaobeneficio['rua'] ?>" name="rua" id="rua">
                                                    <label> Nº: </label>
                                                    <input type="text" disabled class="form-control" value="<?= $solicitacaobeneficio['numero_casa'] ?>" name="numeroCasa" id="numeroCasa">									
                                                    <label> Bairro: </label>
                                                    <input type="text" disabled class="form-control" value="<?= $solicitacaobeneficio['bairro'] ?>" name="bairro" id="bairro">									
                                                    <label >Carteira do Idoso:</label>
                                                    <br>
                                                    <button class="btn" value="<?= $solicitacaobeneficio['carteira_idoso'] ?>" id="carteiraIdoso" name="carteiraIdoso">
                                                        <i class="fa fa-download" style="color:black"></i>
                                                        <label style="color:black">
                                                            <a style="color:black" href="dist/autorizaconcessao/carteiraidoso.pdf"
                                                               download="CarteiraIdoso">Download </a>
                                                        </label>
                                                    </button>
                                                    <br>
                                                    <label >Comprovante de Residência:</label>
                                                    <br>
                                                    <button class="btn" value="<?= $solicitacaobeneficio['comprovante_residencia'] ?>" name="comprovanteResidencia" id="comprovanteResidencia">
                                                        <i class="fa fa-download" style="color:black"></i>
                                                        <label style="color:black">
                                                            <a style="color:black" href="dist/autorizaconcessao/comprovanteresidencia.pdf"
                                                               download="resid">Download </a>
                                                        </label>
                                                    </button>

                                                </div>
                                            </div>

                                        </form>							
                                    </div>
                                </div>
                            </div>			 
                        </div>

                    </div>
                </div>
            </div>
        <? endforeach; ?>


</body>
