<div class="container fundo">
   <div class="row">
	<div class="col-sm-2"> </div>
	  <div class="col-sm-8" >
	  <br> <br> <br>
			
		<div class="card" style="max-width: 400rem; background-color:rgba(0,0,0,0.5); color: white">
				<div class="card-body" >
					<center><h3>Selecione a categoria de passageiro que deseja:</h3></center>
					 <table class="table">
						<tbody class="Active">
						  <tr>
							<td><a href="<?= $this->baseUrl("beneficio/estudante")?>" class="btn btn-block btn-primary" id="estudante"> 
								<i class="fas fa-user-graduate"></i> Estudante
							</a></td>
						  </tr>
						  <tr>
							<td><a href="<?= $this->baseUrl("beneficio/idoso")?>" class="btn btn-block btn-primary" id="idoso">
								<i class="fas fa-hiking"></i> Pessoa Idosa
							</a></td>
						  </tr>
						  <tr>
							<td><a href="<?= $this->baseUrl("beneficio/deficiente")?>" class="btn btn-block btn-primary" id="deficiencia"> 
							<i class="fas fa-wheelchair"></i> Pessoa com Deficiencia
                            </a></td>
						  </tr>
						</tbody>
					</table>
				</div>
			</div>
	  </div>
	<div class="col-sm-2"></div>
  </div>
</div>
