
<!doctype html>
<html lang="pt-br">
    <head>
        <!--<meta name="viewport" content="width=device-width, initial-scale=1.0" charset="UTF-8">-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" charset="UTF-8">
        <title>Controle de Frotas</title>
        <script type="text/javascript">
            var baseUrl = '<?= $this->baseUrl('/') ?>';
        </script>
        <link rel="icon" type="image/png" href=<?= $this->baseUrl("dist/img/") ?> />
        <!--Caminho da public "$this->baseUrl()-->
        <link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/bootstrap.css") ?> />
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">
                PampaBus
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            Início
                            <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->baseUrl("/parada-onibus") ?>">
                            Paradas
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->baseUrl("/tarifas") ?>">
                            Tarifas
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->baseUrl("/tarifas") ?>">
                            Trajeto
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->baseUrl("/tarifas") ?>">
                            Concessões
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <!--Conteudo das páginas-->
        <div style="margin-top: 5%;">
            <?php echo $this->layout()->content; ?>
        </div>

        <script type="text/javascript" src="<?= $this->baseUrl('dist/js/jquery-3.3.1.js') ?>"></script>
        <script type="text/javascript" src="<?= $this->baseUrl('dist/js/bootstrap.js') ?>"></script>
        <script type="text/javascript" src="<?= $this->baseUrl('dist/js/bootbox.min.js') ?>"></script>
        <?= $this->headScript(); ?>
    </body>
</html>