<!doctype html>
<html lang="pt-br">
    <head>
        <!--<meta name="viewport" content="width=device-width, initial-scale=1.0" charset="UTF-8">-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" charset="UTF-8">
        <title>Controle de Frotas</title>
        <script type="text/javascript">
            var baseUrl = '<?= $this->baseUrl('/') ?>';
        </script>
        <link rel="icon" type="image/png" href=<?= $this->baseUrl("dist/img/bus.png") ?> />
        <!--Caminho da public "$this->baseUrl()-->
        <link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/bootstrap-cerulean.css") ?> />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/style.css") ?> />
        <link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/login.css") ?> />
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" href="#">PampaBus</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>

        <!--Conteudo das páginas-->
        <main style="margin-top: 1%;">
            <?php echo $this->layout()->content; ?>
        </main>



        <script type="text/javascript" src="<?= $this->baseUrl('dist/js/jquery-3.3.1.js') ?>"></script>
        <script type="text/javascript" src="<?= $this->baseUrl('dist/js/bootstrap.js') ?>"></script>
        <script type="text/javascript" src="<?= $this->baseUrl('dist/js/bootbox.min.js') ?>"></script>
        <?= $this->headScript(); ?>
    </body>
</html>