<div class="container">
    <div class="row">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Placa</th>
                    <th scope="col">Chassi</th>
                    <th scope="col">Nº Passageiros</th>
                    <th scope="col">Nº Assentos</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>IVK</td>
                    <td>0001</td>
                    <td>55</td>
                    <td>55</td>
                    <td>
                        <button class="btn btn-info">
                            <span class="btn-label-secratario"><i class="fas fa-eye"></i></span>
                            Visualizar Detalhes
                        </button>
                    </td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>IFT</td>
                    <td>0002</td>
                    <td>55</td>
                    <td>55</td>
                    <td>
                        <button class="btn btn-info">
                            <span class="btn-label-secratario"><i class="fas fa-eye"></i></span>
                            Visualizar Detalhes
                        </button>
                    </td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>ITT</td>
                    <td>0003</td>
                    <td>55</td>
                    <td>55</td>
                    <td>
                        <button class="btn btn-info">
                            <span class="btn-label-secratario"><i class="fas fa-eye"></i></span>
                            Visualizar Detalhes
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>