<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/gerirLinhas.css") ?> />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<script src="js/jquery-3.3.1.js"> </script>

<div class="container fundo">
  <div class="row">		
		<div class="col-sm-12" style="background-color:rgba(0,0,0,0.4); color: white">
			<center><H2>Gerir Linhas</h2></center>
			<div class="row"> 
            <div class="col">
						<Center><H4>Linhas</H4></Center>			              
							<div class="col-12">
								<div class="list-group listaDeTrajetos" id="list-tab" role="tablist">
									<a class="list-group-item list-group-item-action" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Linha 1</a>
									<a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Linha 2</a>
									<a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Linha 3</a>
									<a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">Linha 4</a>   
									<a class="list-group-item list-group-item-action" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Linha 5</a>
									<a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Linha 6</a>
									<a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Linha 7</a>
									<a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">Linha 8</a> 
									<a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Linha 9</a>
									<a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Linha 10</a>
									<a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">Linha 11</a> 
								</div>
							</div>
						</div>
            <div class="col">
							<Center><H4>Informações da Linha</H4>
							<div class="container-fluid" role="tablist">
								<div class="panel panel-default" style="color: black;  height: 120px; text-align: justify;" role="tablist">
									<div class="panel-body" >Informações da Linha</div>
								</div>
							</div>
							<div class="btn-group">
								<button type="button" class="btn btn-success">Criar</button>
								<button type="button" class="btn btn-warning">Editar</button>
								<button type="button" class="btn btn-danger">Arquivar</button>
							</div>
							<div class="distanciaDiv">
								<button type="button" class="btn btn-default">Voltar</button>
							</div>
							</Center>
						</div>
						


			</div>
		</div>			
	</div>
</div>