<link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/categoriaPassageiro.css") ?> />

<div class="container fundo">
   <div class="row">
	<div class="col-sm-2"> </div>
	  <div class="col-sm-8" >
	  <br> <br> <br>
			<table class="table table-bordered text-center" style="background-color: white;">
		<tr class="text-primary">
			<th class="cabecalho text-primary active" colspan="4"><center>Selecione a categoria de passageiro que deseja:</center>
			<br>
			
			
			
		

	  
		  <table class="table">
			<tbody class="Active">
			  <tr>
				<td><button type="button" class="btn"><a href=<?= $this->baseUrl("categoriapassageiro/listar-Passageiros")?> id="estudante"> Estudante/Professor </button></td>
			  </tr>
			  <tr>
				<td><button type="button" class="btn"><a href=<?= $this->baseUrl("categoriapassageiro/listar-Passageiros")?> id="idoso">Pessoa Idosa </button></td>
			  </tr>
			  <tr>
				<td><button type="button" class="btn"><a href=<?= $this->baseUrl("categoriapassageiro/listar-Passageiros")?> id="deficiencia"> Pessoa com Deficiência </button> </td>
			  </tr>
			</tbody>
		  </table>
	  </div>
	<div class="col-sm-2"></div>
  </div>
</div>

