<link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/categoriaPassageiro.css") ?> />

<div class="container fundo">
   <div class="row">
	<div class="col-sm-2"> </div>
	  <div class="col-sm-8" >
	  <br> <br> <br>
			
			<div class="card bg-light mb-3" style="max-width: 42rem;">
				<div class="card-body">
					<center><h3>Selecione a categoria de passageiro que deseja:</h3></center>
					 <table class="table">
						<tbody class="Active">
						  <tr>
							<td><button type="button" class="btn"><a href=<?= $this->baseUrl("categoriapassageiro/listar-Passageiros")?> id="estudante"> Estudante/Professor </button></td>
						  </tr>
						  <tr>
							<td><button type="button" class="btn"><a href=<?= $this->baseUrl("categoriapassageiro/listar-Passageiros")?> id="idoso">Pessoa Idosa </button></td>
						  </tr>
						  <tr>
							<td><button type="button" class="btn"><a href=<?= $this->baseUrl("categoriapassageiro/listar-Passageiros")?> id="deficiencia"> Pessoa com Deficiência </button> </td>
						  </tr>
						</tbody>
					</table>
				</div>
			</div>
	  </div>
	<div class="col-sm-2"></div>
  </div>
</div>

