<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/categoriaPassageiro.css") ?> />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

<body>

<div class="container fundo">

	  <div class="table-responsive" style="background-color:rgba(0,0,0,0.5); color: white">
							<table class="table table-bordered text-center" style="background-color:rgba(0,0,0,0.5); color: white">
								<tr class="text-primary">
									<th class="fundoTransparente" colspan="4" style="background-color:rgba(0,0,0,0.5); color: white">
										<center><h3>Novas Solicitações de Benefícios</h3></center>
									</th>
								</tr>
								<tr>
									<th class="fundoTransparente" colspan="1" style="background-color:rgba(0,0,0,0.5); color: white">Nº</th>
									<th class="fundoTransparente" colspan="1" style="background-color:rgba(0,0,0,0.5); color: white"><center>Nome</center></th>
									<th class="fundoTransparente" colspan="1" style="background-color:rgba(0,0,0,0.5); color: white"> <center>Data de Solicitação</center></th>
									<th class="fundoTransparente" colspan="1" style="background-color:rgba(0,0,0,0.5); color: white"><center>Situação</center></th>
								</tr>
								<tr>
									<td class="fundoTransparente">1</td>
									<td> Vagner Ereno Quincozes </td>
									<td> 25/03/2019 </td>
									<td>
										<button class="btn" data-toggle="modal" data-target="#modal-mensagem"> 
											<i class="fas fa-edit"></i>
										</button>
									</td>

								</tr>
								<tr>
									<td class="fundoTransparente">1</td>
									<td> Vagner Ereno Quincozes </td>
									<td> 25/03/2019 </td>
									<td>
										<button class="btn" data-toggle="modal" data-target="#modal-mensagem"> 
											<i class="fas fa-edit"></i>
										</button>
									</td>
								</tr>
								<tr>
									<td class="fundoTransparente">1</td>
									<td> Vagner Ereno Quincozes </td>
									<td> 25/03/2019 </td>
									<td>
										<button class="btn" data-toggle="modal" data-target="#modal-mensagem"> 
											<i class="fas fa-edit"></i>
										</button>
									</td>									
								</tr>
								<tr>
									<td class="fundoTransparente">1</td>
									<td> Vagner Ereno Quincozes </td>
									<td> 25/03/2019 </td>
									<td>
										<button class="btn" data-toggle="modal" data-target="#modal-mensagem"> 
											<i class="fas fa-edit"></i>
										</button>
									</td>
								</tr>
								<tr>
									<td class="fundoTransparente">1</td>
									<td> Vagner Ereno Quincozes </td>
									<td> 25/03/2019 </td>
									<td>
										<button class="btn" data-toggle="modal" data-target="#modal-mensagem"> 
											<i class="fas fa-edit"></i>
										</button>
									</td>
								</tr>
								<tr>
									<td class="fundoTransparente">1</td>
									<td> Vagner Ereno Quincozes </td>
									<td> 25/03/2019 </td>
									<td>
										<button class="btn" data-toggle="modal" data-target="#modal-mensagem"> 
											<i class="fas fa-edit"></i>
										</button>
									</td>
								</tr>
								<tr>
									<td class="fundoTransparente">1</td>
									<td> Vagner Ereno Quincozes </td>
									<td> 25/03/2019 </td>
									<td>
										<button class="btn" data-toggle="modal" data-target="#modal-mensagem"> 
											<i class="fas fa-edit"></i>
										</button>
									</td>
								</tr>
								<tr>
									<td class="fundoTransparente">1</td>
									<td> Vagner Ereno Quincozes </td>
									<td> 25/03/2019 </td>
									<td>
										<button class="btn" data-toggle="modal" data-target="#modal-mensagem"> 
											<i class="fas fa-edit"></i>
										</button>
									</td>
								</tr>
								<tr>
									<td class="fundoTransparente">1</td>
									<td> Vagner Ereno Quincozes </td>
									<td> 25/03/2019 </td>
									<td>
										<button class="btn" data-toggle="modal" data-target="#modal-mensagem"> 
											<i class="fas fa-edit"></i>
										</button>
									</td>								</tr>
								<tr>
									<td class="fundoTransparente">1</td>
									<td> Vagner Ereno Quincozes </td>
									<td> 25/03/2019 </td>
									<td>
										<button class="btn" data-toggle="modal" data-target="#modal-mensagem"> 
											<i class="fas fa-edit"></i>
										</button>
									</td>								</tr>
								<tr>
									<td class="fundoTransparente">1</td>
									<td> Vagner Ereno Quincozes </td>
									<td> 25/03/2019 </td>
									<td>
										<button class="btn" data-toggle="modal" data-target="#modal-mensagem"> 
											<i class="fas fa-edit"></i>
										</button>
									</td>								</tr>
								<tr>
									<td class="fundoTransparente">1</td>
									<td> Vagner  Quincozes </td>
									<td> 25/03/2019 </td>	
									<td>
										<button class="btn" data-toggle="modal" data-target="#modal-mensagem"> 
											<i class="fas fa-edit"></i>
										</button>
									</td>
								 </tr>
							</table>
	  
</div>
	<!-- Modal -->
<div class="modal fade" id="modal-mensagem" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
         <div class="modal-content">
             <div class="modal-header">
			     <h4 class="modal-title">ESTUDANTES/PROFESSORES</h4>
                 <button type="button" class="close" data-dismiss="modal">
					<span>&times;</span>
				 </button>
             </div>
             <div class="modal-body">
				
				<div class="container-fluid"> 
					<div class="row">
						<table class="" style="background-color: white;">
								<tr>
									<td><div style="text-align: right;">Nome completo:&nbsp;</div> </td>
									<td><input type="text" class="form-control" id="nomeCompleto" value="Vagner Ereno Quincozes" style="width:400px;font-size: 15px"></input></td>
								</tr>
								<tr>
									<td><div style="text-align: right;">CPF:&nbsp;</div></td>
									<td><input type="text" class="form-control" id="cpf" value="040.459.542-10" style="width:400px;font-size: 15px"></input></td>
								</tr>
								<tr>
									<td><div style="text-align: right;">Data de Nascimento:&nbsp;</div></td>
									<td><input type="text" class="form-control" id="dataDeNascimento" value="18/05/2017" style="width:400px;font-size: 15px"></input></td>
								</tr>								
								<tr>
									<td><div style="text-align: right;">Comprovante de Matrícula:&nbsp;</div></td>
									<td><button class="btn btn-primary" id="comprovanteDeMatricula"><i class="fas fa-download"> Baixar arquivo PDF.. </i></button> </td>
								</tr>
								<tr>
									<td><div style="text-align: right;">Comprovante de Residência:&nbsp;</div></td>
									<td><button class="btn btn-primary" id="comprovanteDeResidencia"> <i class="fas fa-download"> Baixar arquivo PDF.. </i></button></td>
								</tr>
								<tr>
									<td><div style="text-align: right;">Rua:&nbsp;</div></td>
									<td><input type="text" class="form-control" id="rua" value="Barão do Amazonas" style="width:400px;font-size: 15px"></input></td>
								</tr>
								<tr>
									<td><div style="text-align: right;">Nº:&nbsp;</div></td>
									<td><input type="text" class="form-control" id="numeroCasa" value="210" style="width:400px;font-size: 15px"></input></td>
								</tr>
								<tr>
									<td><div style="text-align: right;">Bairro:&nbsp;</div></td>
									<td><input type="text" class="form-control" id="bairro" value="Centro" style="width:400px;font-size: 15px"></input></td>
								</tr>
								<tr>
									<td><div style="text-align: right;">Celular:&nbsp;</div></td>
									<td><input type="text" class="form-control" id="bairro" value="Centro" style="width:400px;font-size: 15px"></input></td>
									
								</tr>
								<tr>
									<td><div style="text-align: right;">Benefício Concedido:&nbsp;</div></td>
									<td><div class="dropdown">
											<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" id="beneficioConcedido">
												Nenhum
											</button>
											<div class="dropdown-menu">
												<a class="dropdown-item" href="#">Meia-Passagem</a>
												<a class="dropdown-item" href="#">Isenção</a>
											</div>
										</div>
									
								</tr>
						</table>
					</div>
				</div>
				 
				 		 
				 
				 
				 
             </div>
             <div class="modal-footer">
			    <button type="button" class="btn btn-success" data-dismiss="modal">Salvar</button>

                 <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
             </div>
         </div>
    </div>
 </div>


</body>
