  

<div class="container">
    <div class="row">
        <div class="col-lg-12" style="padding: 0px;">
            <ol class="breadcrumb" style="background-color:rgba(0,0,0,0.5);">
                <li class="breadcrumb-item"><a href="<?= $this->baseUrl("admin-local") ?>">Início</a></li>
                <li class="breadcrumb-item"><a href="<?= $this->baseUrl("sinistro") ?>">Sinistros</a></li>
                <li class="breadcrumb-item active" style="color: white;" aria-current="page">Visualizar</li>
            </ol>
        </div>

        <div class="col-lg-12" style="padding: 0px;">

            <div class="card-body">
                <form class="jumbontron" method="post"  style="background-color:rgba(0,0,0,0.5); color: white; padding: 15px;">
                    <div class="form-group">
                        <input type="hidden" id="id_sinistro" value="<? echo $this->sinistro->getId_sinistro() ?>">
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="descricao" id="label">Causa</label><label  style="color:red" id="label"></label>
                                <div style="padding-bottom: 5px">
                                    <input type="text" disabled class="form-control" id="causa" name="causa" value="<? echo $this->sinistro->getCausa() ?>" placeholder="Causa" >
                                </div>
                                <div class="alert-lt alert-danger causa hidden"  align="center" role="alert">
                                    Campo causa obrigatório
                                </div>
                            </div>                                                      

                            <div class="col-lg-4">
                                <label for="descricao" id="label">Culpado</label><label  style="color:red" id="label"></label>
                                <div style="padding-bottom: 5px">
                                    <input type="text" disabled class="form-control" id="culpado" name="culpado" value="<? echo $this->sinistro->getCulpado() ?>" placeholder="Culpado" >
                                </div>
                                <div class="alert-lt alert-danger culpado hidden"  align="center" role="alert">
                                    Campo culpado obrigatório
                                </div>
                            </div>                                                      

                            <div class="col-lg-4">
                                <label for="descricao" id="label">Custo</label><label  style="color:red" id="label"></label>
                                <div style="padding-bottom: 5px">
                                    <input type="text" disabled class="form-control" id="custo" name="custo" value="<? echo $this->sinistro->getCusto() ?>" placeholder="R$" >
                                </div>
                                <div class="alert-lt alert-danger custo hidden"  align="center" role="alert">
                                    Campo custo obrigatório
                                </div>
                            </div>                                                      
                        </div>

                        <div class="row">
                            <div class="col-lg-4">
                                <label for="descricao" id="label">Pagador</label><label  style="color:red" id="label"></label>
                                <div style="padding-bottom: 5px">
                                    <input type="text" disabled class="form-control" id="pagante" name="pagante" value="<? echo $this->sinistro->getPagante() ?>" placeholder="Quem paga" >
                                </div>
                                <div class="alert-lt alert-danger pagante hidden"  align="center" role="alert">
                                    Campo pagador obrigatório
                                </div>
                            </div>                                                      

                            <div class="col-lg-4">
                                <label for="descricao" id="label">Data</label><label  style="color:red" id="label"></label>
                                <div style="padding-bottom: 5px">
                                    <input type="text" disabled class="form-control" id="data" name="data" value="<? echo $this->sinistro->getData() ?>" placeholder="Data" >
                                </div>
                                <div class="alert-lt alert-danger data hidden"  align="center" role="alert">
                                    Campo data obrigatório
                                </div>
                            </div>                                                      

                            <div class="col-lg-4">
                                <label for="hora" id="label">Hora</label><label  style="color:red" id="label"></label>
                                <div style="padding-bottom: 5px">
                                    <input type="time" disabled class="form-control" id="hora" name="hora" value="<? echo $this->sinistro->getHora() ?>" placeholder="Hora" >
                                </div>
                                <div class="alert-lt alert-danger hora hidden"  align="center" role="alert">
                                    Campo hora obrigatório
                                </div>
                            </div>                                                      
                        </div>




                        <div class="row">
                            <div class="col-lg-7">
                                <label for="descricao" id="label">Descrição</label><label  style="color:red" id="label"></label>
                                <div style="padding-bottom: 5px">
                                <textarea id="descricao" disabled name="descricao" rows="3" class="form-control" placeholder="Descrição" data-validation-required-message="Somente números."><? echo $this->sinistro->getDescricao() ?></textarea>
                                </div>
                            </div>

                            <div class="col-lg-5">
                                <label for="descricao" id="label">Ônibus (Modelo/Chassi)</label><label  style="color:red" id="label"></label>
                                <div style="padding-bottom: 5px">
                                    <input type="text" disabled id="descricao" name="descricao" rows="3" value="<? echo $this->sinistro->getOnibus() ?>" class="form-control" placeholder="Descrição"></textarea>
                                </div>

                            </div>
                        </div>

                    </div>	

                </form>
            </div>
        </div>
    </div>


    <!-- fim container form-->


    <!--// AQUI DEVE APARECER TODOS OS ÔNIBUS DISPONÍVEIS-->

    <div class="modal fade" id="exampleModalCenter-inicio" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Selecione o Ônibus</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <div class="modal-body">
                        <select multiple class="form-control" id="sel5" style="height: 270px;">
                            <? foreach ($this->listarTodosOnibusIntermunicipais as $onibus): ?>
                                <option  value="<?= $onibus['id_onibus_viagem'] ?>"><?= $onibus['modelo'] . " " . $onibus['chassi']; ?></option>
                            <? endforeach; ?>

                            <? foreach ($this->listaDosOnibusUrbanos as $onibus1): ?>
                                <option  value="<?= $onibus1['id_onibus_urbano'] ?>"><?= $onibus1['modelo'] . " " . $onibus1['chassi']; ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" id="alocar" data-dismiss="modal">Ok</button>


                    </div>
                </div>
            </div>
        </div>










