<div class="container-fluid">
	<link rel="stylesheet" type="text/css" href=<?= $this->baseUrl("dist/css/forma-pagamento.css") ?> />
  <div class="row" >
    <div class="col-lg-2"></div>
  <div class="col-lg-8">
    <br>
    <br>
 <div class="card mb-3" style="background-color:rgba(0,0,0,0.8);">
    <div class="card-body"> 

      <a href="../public/categoria-onibus" class="btn btn-block btn-primary">Gerenciar Tarifas de Categorias</a>
      <br>
      <a href="../public/parada-onibus" class="btn btn-block btn-primary">Gerenciar paradas de onibus</a>
      <br>
      <a href="../public/forma-pagamento" class="btn btn-block btn-primary">Gerenciar formas de pagamento</a>
</div>
</div>
</div>
    <div class="col-lg-2"></div>

</div>
</div>