<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Início</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Cadastrar Ônibus Urbano</li>
                </ol>
            </nav>
            <form class="jumbotron" method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="col">
                        <label>Placa</label>
                        <input type="text" class="form-control" placeholder="Placa">
                    </div>
                    <div class="col">
                        <label>Chassi</label>
                        <input type="text" class="form-control" placeholder="Chassi">
                    </div>
                    <div class="col">
                        <label>Nº Assentos</label>
                        <input type="text" class="form-control" placeholder="Nº Assentos">
                    </div>
                    <div class="col">
                        <label>Nº Passageiros</label>
                        <input type="text" class="form-control" placeholder="Nº Passageiros">
                    </div>
                </div>
                <hr>
                <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
            </form>
            <!--            <form class="jumbotron" method="post" enctype="multipart/form-data">
                            <div class="form-group col-lg-2">
                                <label for="placa">Placa</label>
                                <input type="text" class="form-control" id="placa">
                            </div>
                            <div class="form-group col-lg-2">
                                <label for="exampleInputPassword1">Chassi</label>
                                <input type="text" class="form-control" id="chassi">
                            </div>
                            <div class="form-group col-lg-2">
                                <label for="numero_assentos">Número de Assentos</label>
                                <input type="text" class="form-control" id="numero_assentos">
                            </div>
                            <div class="form-group col-lg-2">
                                <label for="numero_passageiros">Número de Passageiros</label>
                                <input type="text" class="form-control" id="numero_passageiros">
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
                        </form>-->
        </div>
        <div class="col-lg-2"></div>
    </div>
</div>

