<div class="container">
    <div class="row">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Placa</th>
                    <th scope="col">Marca</th>
                    <th scope="col">Modelo</th>
                    <th scope="col">Chassi</th>
                    <th scope="col">Nº Passageiros</th>
                    <th scope="col">Nº Assentos</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>IHJ</td>
                    <td>Volkswagen</td>
                    <td>ISF</td>
                    <td>0004</td>
                    <td>40</td>
                    <td>47</td>
                    <td>
                        <button class="btn btn-info">
                            <i class="fas fa-eye"></i>
                            Visualizar Detalhes
                        </button>
                    </td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>IFT</td>
                    <td>Volkswagen</td>
                    <td>ISF</td>
                    <td>0005</td>
                    <td>40</td>
                    <td>47</td>
                    <td>
                        <button class="btn btn-info">
                            <i class="fas fa-eye"></i>
                            Visualizar Detalhes
                        </button>
                    </td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>ITT</td>
                    <td>Mercedes Benz</td>
                    <td>LO815</td>
                    <td>0006</td>
                    <td>40</td>
                    <td>47</td>
                    <td>
                        <button class="btn btn-info">
                            <i class="fas fa-eye"></i>
                            Visualizar Detalhes
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>