<div class="container">
    <div class="row">
        <div class="col-lg-12" style="padding: 0px;">
            <ol class="breadcrumb" style="background-color:rgba(0,0,0,0.5);">
                <li class="breadcrumb-item"><a href="<?= $this->baseUrl("admin-local") ?>">Início</a></li>
                <li class="breadcrumb-item"><a href="<?= $this->baseUrl("manutencao") ?>">Manutenções</a></li>
                <li class="breadcrumb-item active" style="color: white;" aria-current="page">Visualizar</li>
            </ol>
        </div>

        <div class="col-lg-12" style="background-color:rgba(0,0,0,0.5);">
            <? foreach ($this->manutencaoPorId as $manutencao): ?>
            <hr>
                <h5 style="color: white;"><strong style="color: white;">Descrição da manutenção: </strong><? echo $manutencao['descricao'] ?></h5>
                <h5 style="color: white;"><strong style="color: white;">Concluida em: </strong><? echo $manutencao['data_fim'] ?></h5>
            <? endforeach; ?>

            <table class="table" style="text-align: center; margin-top: 2%; background-color:rgba(0,0,0,0.5); padding: 0px; color: white;">
                <thead >
                    <tr>
                        <th>Placa</th>
                        <th>Ano</th>
                        <th>Tipo</th>
                    </tr>
                </thead>
                <tbody>

                    <? foreach ($this->listarOnibusPorIdManutencao as $onibus): ?>
                        <tr>
                            <td><?= $onibus['placa'] ?></td>
                            <td><?= $onibus['ano'] ?></td>
                            <td><?= $onibus['tipo'] ?></td>
                        </tr>
                    <? endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>